/*
 * AdminUIAboutBox.java
 */

package com.whelanlabs.searchengine;

import java.awt.Cursor;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.application.Action;

public class AdminUIAboutBox extends javax.swing.JDialog {

    public AdminUIAboutBox(java.awt.Frame parent) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
    }

    @Action public void closeAboutBox() {
        setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      closeButton = new javax.swing.JButton();
      javax.swing.JLabel appTitleLabel = new javax.swing.JLabel();
      javax.swing.JLabel versionLabel = new javax.swing.JLabel();
      javax.swing.JLabel appVersionLabel = new javax.swing.JLabel();
      javax.swing.JLabel vendorLabel = new javax.swing.JLabel();
      javax.swing.JLabel appVendorLabel = new javax.swing.JLabel();
      javax.swing.JLabel homepageLabel = new javax.swing.JLabel();
      javax.swing.JLabel appHomepageLabel = new javax.swing.JLabel();
      javax.swing.JLabel appDescLabel = new javax.swing.JLabel();
      javax.swing.JLabel imageLabel = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.whelanlabs.searchengine.AdminUI.class).getContext().getResourceMap(AdminUIAboutBox.class);
      setTitle(resourceMap.getString("title")); // NOI18N
      setModal(true);
      setName("aboutBox"); // NOI18N
      setResizable(false);

      javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.whelanlabs.searchengine.AdminUI.class).getContext().getActionMap(AdminUIAboutBox.class, this);
      closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
      closeButton.setName("closeButton"); // NOI18N

      appTitleLabel.setFont(appTitleLabel.getFont().deriveFont(appTitleLabel.getFont().getStyle() | java.awt.Font.BOLD, appTitleLabel.getFont().getSize()+4));
      appTitleLabel.setText(resourceMap.getString("Application.title")); // NOI18N
      appTitleLabel.setName("appTitleLabel"); // NOI18N

      versionLabel.setFont(versionLabel.getFont().deriveFont(versionLabel.getFont().getStyle() | java.awt.Font.BOLD));
      versionLabel.setText(resourceMap.getString("versionLabel.text")); // NOI18N
      versionLabel.setName("versionLabel"); // NOI18N

      appVersionLabel.setText(resourceMap.getString("Application.version")); // NOI18N
      appVersionLabel.setName("appVersionLabel"); // NOI18N

      vendorLabel.setFont(vendorLabel.getFont().deriveFont(vendorLabel.getFont().getStyle() | java.awt.Font.BOLD));
      vendorLabel.setText(resourceMap.getString("vendorLabel.text")); // NOI18N
      vendorLabel.setName("vendorLabel"); // NOI18N

      appVendorLabel.setText(resourceMap.getString("Application.vendor")); // NOI18N
      appVendorLabel.setName("appVendorLabel"); // NOI18N

      homepageLabel.setFont(homepageLabel.getFont().deriveFont(homepageLabel.getFont().getStyle() | java.awt.Font.BOLD));
      homepageLabel.setText(resourceMap.getString("homepageLabel.text")); // NOI18N
      homepageLabel.setName("homepageLabel"); // NOI18N

      appHomepageLabel.setForeground(resourceMap.getColor("appHomepageLabel.foreground")); // NOI18N
      appHomepageLabel.setText(resourceMap.getString("Application.homepage")); // NOI18N
      appHomepageLabel.setName("appHomepageLabel"); // NOI18N
      appHomepageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            appHomepageLabelMouseEntered(evt);
         }
         public void mousePressed(java.awt.event.MouseEvent evt) {
            appHomepageLabelMousePressed(evt);
         }
      });

      appDescLabel.setText(resourceMap.getString("appDescLabel.text")); // NOI18N
      appDescLabel.setName("appDescLabel"); // NOI18N

      imageLabel.setIcon(resourceMap.getIcon("imageLabel.icon")); // NOI18N
      imageLabel.setName("imageLabel"); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(imageLabel)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(versionLabel)
                     .addComponent(vendorLabel)
                     .addComponent(homepageLabel))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(appVendorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(appHomepageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(appVersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
               .addComponent(appDescLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
               .addComponent(closeButton)
               .addComponent(appTitleLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, Short.MAX_VALUE)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(appTitleLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(appDescLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(versionLabel)
               .addComponent(appVersionLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(vendorLabel)
               .addComponent(appVendorLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(homepageLabel)
               .addComponent(appHomepageLabel))
            .addGap(76, 76, Short.MAX_VALUE)
            .addComponent(closeButton)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

private void appHomepageLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appHomepageLabelMousePressed
      try {
         String url = "http://www.whelanlabs.com";
         URI uri = new URI(url);
         java.awt.Desktop desktop = Desktop.getDesktop();
         desktop.browse(uri);
      } catch (IOException ex) {
         Logger.getLogger(AdminUIView.class.getName()).log(Level.SEVERE, null, ex);
      } catch (URISyntaxException ex) {
         Logger.getLogger(AdminUIView.class.getName()).log(Level.SEVERE, null, ex);
      }
}//GEN-LAST:event_appHomepageLabelMousePressed

private void appHomepageLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appHomepageLabelMouseEntered
   Cursor hourglassCursor = new Cursor(Cursor.HAND_CURSOR);
   evt.getComponent().setCursor(hourglassCursor);
}//GEN-LAST:event_appHomepageLabelMouseEntered
    
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton closeButton;
   // End of variables declaration//GEN-END:variables
    
}
