/*
 * ProxyConfigurationDialog.java
 *
 * Created on March 26, 2009, 11:59 PM
 */

package com.whelanlabs.searchengine;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author  john
 */
public class ProxyConfigurationDialog extends javax.swing.JDialog {
   private String appRootDirectory;

    /** Creates new form ProxyConfigurationDialog */
    //public ProxyConfigurationDialog(java.awt.Frame parent, boolean modal) {
    //    super(parent, modal);
    //    initComponents();
    //}
    
    // appRootDirectory
    /** Creates new form ProxyConfigurationDialog */
    public ProxyConfigurationDialog(java.awt.Frame parent, boolean modal, String appRootDir) {
        super(parent, modal);
        initComponents();
        appRootDirectory = appRootDir;
        setValues();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      hostnameTextField = new javax.swing.JTextField();
      usernameTextField = new javax.swing.JTextField();
      jLabel4 = new javax.swing.JLabel();
      proxyEnabledCheckBox = new javax.swing.JCheckBox();
      jLabel5 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      passwordField = new javax.swing.JPasswordField();
      portTextField = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      jPanel2 = new javax.swing.JPanel();
      proxyConfigCancelButton = new javax.swing.JButton();
      proxyConfigOKButton = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.whelanlabs.searchengine.AdminUI.class).getContext().getResourceMap(ProxyConfigurationDialog.class);
      setTitle(resourceMap.getString("Form.title")); // NOI18N
      setName("Form"); // NOI18N
      setResizable(false);

      jPanel1.setName("jPanel1"); // NOI18N

      hostnameTextField.setText(resourceMap.getString("hostnameTextField.text")); // NOI18N
      hostnameTextField.setName("hostnameTextField"); // NOI18N

      usernameTextField.setText(resourceMap.getString("usernameTextField.text")); // NOI18N
      usernameTextField.setName("usernameTextField"); // NOI18N

      jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
      jLabel4.setName("jLabel4"); // NOI18N

      proxyEnabledCheckBox.setText(resourceMap.getString("proxyEnabledCheckBox.text")); // NOI18N
      proxyEnabledCheckBox.setName("proxyEnabledCheckBox"); // NOI18N
      proxyEnabledCheckBox.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            proxyEnabledCheckBoxActionPerformed(evt);
         }
      });

      jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
      jLabel5.setName("jLabel5"); // NOI18N

      jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
      jLabel2.setName("jLabel2"); // NOI18N

      jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
      jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
      jLabel3.setName("jLabel3"); // NOI18N

      passwordField.setText(resourceMap.getString("passwordField.text")); // NOI18N
      passwordField.setName("passwordField"); // NOI18N

      portTextField.setText(resourceMap.getString("portTextField.text")); // NOI18N
      portTextField.setName("portTextField"); // NOI18N

      jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
      jLabel1.setName("jLabel1"); // NOI18N

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                           .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(10, 10, 10))
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                     .addComponent(hostnameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                     .addComponent(portTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                     .addComponent(usernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(proxyEnabledCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(proxyEnabledCheckBox)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(hostnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel5))
            .addContainerGap())
      );

      jPanel2.setName("jPanel2"); // NOI18N

      proxyConfigCancelButton.setText(resourceMap.getString("proxyConfigCancelButton.text")); // NOI18N
      proxyConfigCancelButton.setMaximumSize(new java.awt.Dimension(105, 23));
      proxyConfigCancelButton.setMinimumSize(new java.awt.Dimension(105, 23));
      proxyConfigCancelButton.setName("proxyConfigCancelButton"); // NOI18N
      proxyConfigCancelButton.setPreferredSize(new java.awt.Dimension(105, 23));
      proxyConfigCancelButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            proxyConfigCancelButtonActionPerformed(evt);
         }
      });

      proxyConfigOKButton.setText(resourceMap.getString("proxyConfigOKButton.text")); // NOI18N
      proxyConfigOKButton.setMaximumSize(new java.awt.Dimension(105, 23));
      proxyConfigOKButton.setMinimumSize(new java.awt.Dimension(105, 23));
      proxyConfigOKButton.setName("proxyConfigOKButton"); // NOI18N
      proxyConfigOKButton.setPreferredSize(new java.awt.Dimension(105, 23));
      proxyConfigOKButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            proxyConfigOKButtonActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(215, Short.MAX_VALUE)
            .addComponent(proxyConfigOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(proxyConfigCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(proxyConfigCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(proxyConfigOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

private void proxyEnabledCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxyEnabledCheckBoxActionPerformed
   setmodifyableOrNot();
}//GEN-LAST:event_proxyEnabledCheckBoxActionPerformed

private void proxyConfigOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxyConfigOKButtonActionPerformed
  setVisible(false);
  
   Properties properties = new Properties();
   if (proxyEnabledCheckBox.isSelected()) {
      properties.setProperty("proxyEnabled", "true");
   }
   else {
      properties.setProperty("proxyEnabled", "false");
   }
   
   properties.setProperty("proxyHost", hostnameTextField.getText());
   properties.setProperty("proxyPort", portTextField.getText());
   properties.setProperty("proxyUser", usernameTextField.getText());
   properties.setProperty("proxyPassword", passwordField.getText());

   try {
      String filename = appRootDirectory + "/config/proxy.properties";
      properties.store(new FileOutputStream(filename), null);
   } catch (IOException ex) {
      Logger.getLogger(AdminUIView.class.getName()).log(Level.SEVERE, null, ex);
   }
  
   TemplateUtils.updateNutchConfig(appRootDirectory);

}//GEN-LAST:event_proxyConfigOKButtonActionPerformed

private void proxyConfigCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxyConfigCancelButtonActionPerformed
  setVisible(false);
  //TODO: set the values back to the previous values?

}//GEN-LAST:event_proxyConfigCancelButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProxyConfigurationDialog dialog = new ProxyConfigurationDialog(new javax.swing.JFrame(), true, "C:\\WhelanLabs\\SearchEngine");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTextField hostnameTextField;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPasswordField passwordField;
   private javax.swing.JTextField portTextField;
   private javax.swing.JButton proxyConfigCancelButton;
   private javax.swing.JButton proxyConfigOKButton;
   private javax.swing.JCheckBox proxyEnabledCheckBox;
   private javax.swing.JTextField usernameTextField;
   // End of variables declaration//GEN-END:variables

   private void setValues() {
      Properties properties = new Properties();
      try {
         String filename = appRootDirectory + "/config/proxy.properties";
         properties.load(new FileInputStream(filename));
      } catch (IOException ex) {
         Logger.getLogger(AdminUIView.class.getName()).log(Level.SEVERE, null, ex);
      }

      hostnameTextField.setText(properties.getProperty("proxyHost"));
      portTextField.setText(properties.getProperty("proxyPort"));
      usernameTextField.setText(properties.getProperty("proxyUser"));
      passwordField.setText(properties.getProperty("proxyPassword"));
      if ("true".equals(properties.getProperty("proxyEnabled"))) {
         proxyEnabledCheckBox.setSelected(true);
      } else {
         proxyEnabledCheckBox.setSelected(false);
      }
      setmodifyableOrNot();
   }
  
   private void setmodifyableOrNot() {
      // if selected, dialogs are modifyable, else they are not
      if (!proxyEnabledCheckBox.isSelected()) {
         hostnameTextField.setEnabled(false);
         passwordField.setEnabled(false);
         portTextField.setEnabled(false);
         usernameTextField.setEnabled(false);
      } else {
         hostnameTextField.setEnabled(true);
         passwordField.setEnabled(true);
         portTextField.setEnabled(true);
         usernameTextField.setEnabled(true);
      }
   }
}
